-- METADATA STATUS
CREATE TABLE metadata_status (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    path_category VARCHAR(255) NOT NULL,
    path VARCHAR(1024) NOT NULL,
    is_available TINYINT(1) NOT NULL,
    meta_data JSON NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- MEDIA CATALOG
CREATE TABLE media_catalog (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    media_type VARCHAR(255) NOT NULL COMMENT 'MOVIE, WEB-SERIES, DOCUMENTARY',
    media_name VARCHAR(255) NOT NULL,
    language VARCHAR(255) NOT NULL,
    is_downloaded TINYINT(1) NOT NULL,
    download_path BIGINT UNSIGNED NULL,
    main_genres VARCHAR(255) NOT NULL,
    sub_genres VARCHAR(255) NOT NULL,
    available_on BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_media_name (media_name),
    INDEX idx_media_type (media_type),
    INDEX idx_language (language),
    CONSTRAINT fk_media_download_path FOREIGN KEY (download_path) REFERENCES metadata_status(id) ON UPDATE CASCADE ON DELETE SET NULL
);

-- CONTENT CATALOG
CREATE TABLE content_catalog (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    link VARCHAR(255) NOT NULL,
    media_id BIGINT UNSIGNED NULL,
    status VARCHAR(20) NOT NULL,
    priority VARCHAR(20) NOT NULL,
    local_status VARCHAR(20) NOT NULL COMMENT 'IS LINK DOWNLOADED OR NOT',
    local_file_path BIGINT UNSIGNED NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT chk_content_status CHECK (UPPER(status) IN ('NEW','DOWNLOADED','ERROR')),
    CONSTRAINT chk_content_priority CHECK (UPPER(priority) IN ('LOW','MEDIUM','HIGH')),
    CONSTRAINT chk_content_local_status CHECK (UPPER(local_status) IN ('DOWNLOADED','ERROR','NA')),
    CONSTRAINT fk_content_media FOREIGN KEY (media_id) REFERENCES media_catalog(id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_content_local_file FOREIGN KEY (local_file_path) REFERENCES metadata_status(id) ON UPDATE CASCADE ON DELETE SET NULL
);

-- UPLOAD CATALOG
CREATE TABLE upload_catalog (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    source_link_id BIGINT UNSIGNED NULL,
    source_data BIGINT UNSIGNED NOT NULL COMMENT 'SOURCE METADATA FOR CONTENT WITH LOCATION',
    status VARCHAR(30) NOT NULL,
    media_id BIGINT UNSIGNED NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT chk_upload_status CHECK (UPPER(status) IN ('COMPLETED','DOWNLOADED','IN-PROGRESS','BLOCKED','READY-TO-UPLOAD','UPLOADED')),
    CONSTRAINT fk_upload_source_data FOREIGN KEY (source_data) REFERENCES metadata_status(id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_upload_source_link FOREIGN KEY (source_link_id) REFERENCES content_catalog(id) ON UPDATE CASCADE ON DELETE SET NULL,
    CONSTRAINT fk_upload_media FOREIGN KEY (media_id) REFERENCES media_catalog(id) ON UPDATE CASCADE ON DELETE SET NULL
);

-- STATS CATALOG
CREATE TABLE stats_catalog (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    date DATE NOT NULL,
    total_views DOUBLE NOT NULL,
    subscribers DOUBLE NOT NULL,
    interaction DOUBLE NOT NULL,
    content_id BIGINT UNSIGNED NULL,
    page VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT chk_stats_page CHECK (UPPER(page) IN ('CINE.MITR','CINE.MITR.MUSIC')),
    CONSTRAINT fk_stats_content FOREIGN KEY (content_id) REFERENCES content_catalog(id) ON UPDATE CASCADE ON DELETE SET NULL,
    UNIQUE KEY uq_stats_day_page (date,page)
);
